# Generated by Django 4.1 on 2022-09-30 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supermercado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='CLI_AD_User',
            new_name='CLI_AD_User_id',
        ),
        migrations.AlterField(
            model_name='customers',
            name='CLI_CellPhone',
            field=models.TextField(max_length=15, unique=True),
        ),
    ]
