# Generated by Django 4.1 on 2022-10-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Supermercado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='EM_NIT',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
